### ISSUE TITLE
Error importing with numpy 2

### ISSUE THREAD

**Issue by dstansby** [seung-lab/zmesh#42]
If I try and install `zmesh` with numpy 2, I get the error

```

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/dstansby/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/Users/dstansby/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/Users/dstansby/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/70/p30g5m5d3z168wzk95frpv3h0000gn/T/ipykernel_58629/459358664.py", line 3, in <module>
    import igneous.task_creation as tc
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/igneous/__init__.py", line 1, in <module>
    from zmesh import Mesher
  File "/Users/dstansby/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/zmesh/__init__.py", line 2, in <module>
    from zmesh._zmesh import *

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 3
      1 from cloudvolume import CloudVolume
      2 from taskqueue import LocalTaskQueue
----> 3 import igneous.task_creation as tc
      4 import zarr

File ~/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/igneous/__init__.py:1
----> 1 from zmesh import Mesher
      2 from taskqueue import MockTaskQueue, TaskQueue, RegisteredTask
      3 from .tasks import *

File ~/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/zmesh/__init__.py:2
      1 from zmesh.mesh import Mesh
----> 2 from zmesh._zmesh import *
      4 __version__ = '1.7.0'

File ~/notebooks/hipct/meshgen/.venv/lib/python3.12/site-packages/zmesh/_zmesh.pyx:1, in init zmesh._zmesh()

ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by william-silversmith** [comment]
Oh hi! Are you still having this issue? I pushed an update a few weeks ago and that should have fixed it.

**Comment by william-silversmith** [comment]
Gonna call this fixed. Please reopen if you have a problem!
